name: Tests

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2, 8.1, 8.0, 7.4 ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - uses: actions/checkout@v2

      - uses: symfonycorp/security-checker-action@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip, pcntl
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install Composer dependencies
        run: composer install -n

      - name: Validate composer.lock
        run: composer validate --strict

      - name: Run cs fixer
        run: vendor/bin/php-cs-fixer fix --dry-run

      - name: Run Phpstan
        run: vendor/bin/phpstan --no-progress --debug --memory-limit=1G

      - name: Run tests
        run: vendor/bin/phpunit tests
